### PR TITLE
Submission of my tutorial for the Cookbook Jam 3

### PR DESCRIPTION
**Pull request by rooksword**
Hopefully everything was done right :)

### CODE REVIEW

**Comment by tabularelf** [comment]
Hey! Been taking a gander at this, and I gotta say, it's pretty well done. :) 
I do wanna give a couple of my own notes into this however, particularly on methods.

1. I've noticed that you've defined your methods outside of the create event in your tutorial. Which I can understand the reasoning for it, and the effects on it aren't super drastic for a tutorial, it can have a slight impact on performance as it's effectively making a new method on every frame. So I think at minimal, it's something to keep in mind in terms of code structure. 

2. I would also suggest outright avoiding using the script function syntax anywhere that would be presumably an instance variable. As GameMaker does technically make it global (it's not the case entirely right now as it's a bug, and won't appear til 2024.10 https://github.com/YoYoGames/GameMaker-Bugs/issues/7125. Ultimately, the syntax itself should be `Jump = function() {}` for methods, and `function Jump() {}` for functions. 

I don't mind 1 so much, but I'd recommend at least adjusting 2 as 2 could have some other dire consequences if someone wants to define more than one Jump method for their instances.

**Comment by tabularelf** [comment]
Hey! Been taking a gander at this, and I gotta say, it's pretty well done. :) 
I do wanna give a couple of my own notes into this however, particularly on methods.

1. I've noticed that you've defined your methods outside of the create event in your tutorial. Which I can understand the reasoning for it, and the effects on it aren't super drastic for a tutorial, it can have a slight impact on performance as it's effectively making a new method on every frame. So I think at minimal, it's something to keep in mind in terms of code structure. 

2. I would also suggest outright avoiding using the script function syntax anywhere that would be presumably an instance variable. As GameMaker does technically make it global (it's not the case entirely right now as it's a bug, and won't appear til 2024.10 https://github.com/YoYoGames/GameMaker-Bugs/issues/7125. Ultimately, the syntax itself should be `Jump = function() {}` for methods, and `function Jump() {}` for functions. 

I don't mind 1 so much, but I'd recommend at least correcting 2, as it could have some other dire consequences if someone wants to define more than one Jump method for their instances. I'll leave this open in the meantime so you can have a chance to correct it.

Other than that, this is looking pretty good overall. Very informative. Well done! :)

**Comment by rooksword** [comment]
I reckon it's better now, thanks for the input 👍 
image

**Comment by tabularelf** [comment]
Looking good 😎

**Pull request merged**
